version: '3'
services:
  frontend_dev:
    stdin_open: true
    tty: true
    image: client-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: frontend-dev
    ports:
      - "4000:5173"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true