import React, { useState, useMemo } from "react";
import Table from "../../Table";
import { Icon } from "@iconify/react";
import SaveUser from "./SaveUser";
import { Column } from "react-table";

const Users = () => {
  const [openModal, setOpenModal] = useState<boolean>(false);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const columns = useMemo<Column<any>[]>(
    () => [
      { Header: "ID", accessor: "id" },
      { Header: "Name", accessor: "name" },
      { Header: "Age", accessor: "age" },
      { Header: "Email", accessor: "email" },
    ],
    []
  );

  const data = [
    { id: 1, name: "John Doe", age: 25, email: "john.doe@example.com" },
    { id: 2, name: "Jane Doe", age: 30, email: "jane.doe@example.com" },
    { id: 3, name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
    {
      id: 4,
      name: "Alice Johnson",
      age: 28,
      email: "alice.johnson@example.com",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 32,
      email: "michael.brown@example.com",
    },
    { id: 6, name: "Sarah Davis", age: 27, email: "sarah.davis@example.com" },
    { id: 7, name: "James Wilson", age: 29, email: "james.wilson@example.com" },
    { id: 8, name: "Linda Taylor", age: 31, email: "linda.taylor@example.com" },
    { id: 9, name: "David Lee", age: 26, email: "david.lee@example.com" },
    {
      id: 10,
      name: "Karen Anderson",
      age: 34,
      email: "karen.anderson@example.com",
    },
    {
      id: 11,
      name: "Paul Jackson",
      age: 33,
      email: "paul.jackson@example.com",
    },
    {
      id: 12,
      name: "Emily Harris",
      age: 29,
      email: "emily.harris@example.com",
    },
    {
      id: 13,
      name: "Christopher Young",
      age: 36,
      email: "christopher.young@example.com",
    },
    {
      id: 14,
      name: "Amanda Clark",
      age: 31,
      email: "amanda.clark@example.com",
    },
    {
      id: 15,
      name: "Matthew Turner",
      age: 30,
      email: "matthew.turner@example.com",
    },
    {
      id: 16,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 17, name: "Brian White", age: 28, email: "brian.white@example.com" },
    {
      id: 18,
      name: "Susan Harris",
      age: 35,
      email: "susan.harris@example.com",
    },
    {
      id: 19,
      name: "Daniel Taylor",
      age: 26,
      email: "daniel.taylor@example.com",
    },
    {
      id: 20,
      name: "Jessica Thompson",
      age: 32,
      email: "jessica.thompson@example.com",
    },
    { id: 21, name: "Mark Davis", age: 30, email: "mark.davis@example.com" },
    {
      id: 22,
      name: "Lisa Johnson",
      age: 29,
      email: "lisa.johnson@example.com",
    },
    {
      id: 23,
      name: "Robert Anderson",
      age: 33,
      email: "robert.anderson@example.com",
    },
    {
      id: 24,
      name: "Melissa Jackson",
      age: 31,
      email: "melissa.jackson@example.com",
    },
    {
      id: 25,
      name: "James Wilson",
      age: 27,
      email: "james.wilson@example.com",
    },
    {
      id: 26,
      name: "Jessica Taylor",
      age: 28,
      email: "jessica.taylor@example.com",
    },
    { id: 27, name: "Andrew Lee", age: 34, email: "andrew.lee@example.com" },
    { id: 28, name: "Sarah Brown", age: 25, email: "sarah.brown@example.com" },
    {
      id: 29,
      name: "Michael Johnson",
      age: 26,
      email: "michael.johnson@example.com",
    },
    { id: 30, name: "Emily Davis", age: 32, email: "emily.davis@example.com" },
    {
      id: 31,
      name: "David Harris",
      age: 30,
      email: "david.harris@example.com",
    },
    {
      id: 32,
      name: "Karen Wilson",
      age: 29,
      email: "karen.wilson@example.com",
    },
    {
      id: 33,
      name: "Christopher Martinez",
      age: 35,
      email: "christopher.martinez@example.com",
    },
    {
      id: 34,
      name: "Amanda Clark",
      age: 33,
      email: "amanda.clark@example.com",
    },
    {
      id: 35,
      name: "Matthew Turner",
      age: 28,
      email: "matthew.turner@example.com",
    },
    {
      id: 36,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 37, name: "Brian White", age: 36, email: "brian.white@example.com" },
    {
      id: 38,
      name: "Susan Harris",
      age: 32,
      email: "susan.harris@example.com",
    },
    {
      id: 39,
      name: "Daniel Taylor",
      age: 31,
      email: "daniel.taylor@example.com",
    },
    {
      id: 40,
      name: "Jessica Thompson",
      age: 29,
      email: "jessica.thompson@example.com",
    },
    { id: 41, name: "Mark Davis", age: 25, email: "mark.davis@example.com" },
    {
      id: 42,
      name: "Lisa Johnson",
      age: 26,
      email: "lisa.johnson@example.com",
    },
    {
      id: 43,
      name: "Robert Anderson",
      age: 34,
      email: "robert.anderson@example.com",
    },
    {
      id: 44,
      name: "Melissa Jackson",
      age: 33,
      email: "melissa.jackson@example.com",
    },
    {
      id: 45,
      name: "James Wilson",
      age: 28,
      email: "james.wilson@example.com",
    },
    {
      id: 46,
      name: "Jessica Taylor",
      age: 27,
      email: "jessica.taylor@example.com",
    },
    { id: 47, name: "Andrew Lee", age: 35, email: "andrew.lee@example.com" },
    { id: 48, name: "Sarah Brown", age: 30, email: "sarah.brown@example.com" },
    {
      id: 49,
      name: "Michael Johnson",
      age: 29,
      email: "michael.johnson@example.com",
    },
    { id: 50, name: "Emily Davis", age: 31, email: "emily.davis@example.com" },
    { id: 1, name: "John Doe", age: 25, email: "john.doe@example.com" },
    { id: 2, name: "Jane Doe", age: 30, email: "jane.doe@example.com" },
    { id: 3, name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
    {
      id: 4,
      name: "Alice Johnson",
      age: 28,
      email: "alice.johnson@example.com",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 32,
      email: "michael.brown@example.com",
    },
    { id: 6, name: "Sarah Davis", age: 27, email: "sarah.davis@example.com" },
    { id: 7, name: "James Wilson", age: 29, email: "james.wilson@example.com" },
    { id: 8, name: "Linda Taylor", age: 31, email: "linda.taylor@example.com" },
    { id: 9, name: "David Lee", age: 26, email: "david.lee@example.com" },
    {
      id: 10,
      name: "Karen Anderson",
      age: 34,
      email: "karen.anderson@example.com",
    },
    {
      id: 11,
      name: "Paul Jackson",
      age: 33,
      email: "paul.jackson@example.com",
    },
    {
      id: 12,
      name: "Emily Harris",
      age: 29,
      email: "emily.harris@example.com",
    },
    {
      id: 13,
      name: "Christopher Young",
      age: 36,
      email: "christopher.young@example.com",
    },
    {
      id: 14,
      name: "Amanda Clark",
      age: 31,
      email: "amanda.clark@example.com",
    },
    {
      id: 15,
      name: "Matthew Turner",
      age: 30,
      email: "matthew.turner@example.com",
    },
    {
      id: 16,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 17, name: "Brian White", age: 28, email: "brian.white@example.com" },
    {
      id: 18,
      name: "Susan Harris",
      age: 35,
      email: "susan.harris@example.com",
    },
    {
      id: 19,
      name: "Daniel Taylor",
      age: 26,
      email: "daniel.taylor@example.com",
    },
    {
      id: 20,
      name: "Jessica Thompson",
      age: 32,
      email: "jessica.thompson@example.com",
    },
    { id: 21, name: "Mark Davis", age: 30, email: "mark.davis@example.com" },
    {
      id: 22,
      name: "Lisa Johnson",
      age: 29,
      email: "lisa.johnson@example.com",
    },
    {
      id: 23,
      name: "Robert Anderson",
      age: 33,
      email: "robert.anderson@example.com",
    },
    {
      id: 24,
      name: "Melissa Jackson",
      age: 31,
      email: "melissa.jackson@example.com",
    },
    {
      id: 25,
      name: "James Wilson",
      age: 27,
      email: "james.wilson@example.com",
    },
    {
      id: 26,
      name: "Jessica Taylor",
      age: 28,
      email: "jessica.taylor@example.com",
    },
    { id: 27, name: "Andrew Lee", age: 34, email: "andrew.lee@example.com" },
    { id: 28, name: "Sarah Brown", age: 25, email: "sarah.brown@example.com" },
    {
      id: 29,
      name: "Michael Johnson",
      age: 26,
      email: "michael.johnson@example.com",
    },
    { id: 30, name: "Emily Davis", age: 32, email: "emily.davis@example.com" },
    {
      id: 31,
      name: "David Harris",
      age: 30,
      email: "david.harris@example.com",
    },
    {
      id: 32,
      name: "Karen Wilson",
      age: 29,
      email: "karen.wilson@example.com",
    },
    {
      id: 33,
      name: "Christopher Martinez",
      age: 35,
      email: "christopher.martinez@example.com",
    },
    {
      id: 34,
      name: "Amanda Clark",
      age: 33,
      email: "amanda.clark@example.com",
    },
    {
      id: 35,
      name: "Matthew Turner",
      age: 28,
      email: "matthew.turner@example.com",
    },
    {
      id: 36,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 37, name: "Brian White", age: 36, email: "brian.white@example.com" },
    {
      id: 38,
      name: "Susan Harris",
      age: 32,
      email: "susan.harris@example.com",
    },
    {
      id: 39,
      name: "Daniel Taylor",
      age: 31,
      email: "daniel.taylor@example.com",
    },
    {
      id: 40,
      name: "Jessica Thompson",
      age: 29,
      email: "jessica.thompson@example.com",
    },
    { id: 41, name: "Mark Davis", age: 25, email: "mark.davis@example.com" },
    {
      id: 42,
      name: "Lisa Johnson",
      age: 26,
      email: "lisa.johnson@example.com",
    },
    {
      id: 43,
      name: "Robert Anderson",
      age: 34,
      email: "robert.anderson@example.com",
    },
    {
      id: 44,
      name: "Melissa Jackson",
      age: 33,
      email: "melissa.jackson@example.com",
    },
    {
      id: 45,
      name: "James Wilson",
      age: 28,
      email: "james.wilson@example.com",
    },
    {
      id: 46,
      name: "Jessica Taylor",
      age: 27,
      email: "jessica.taylor@example.com",
    },
    { id: 47, name: "Andrew Lee", age: 35, email: "andrew.lee@example.com" },
    { id: 48, name: "Sarah Brown", age: 30, email: "sarah.brown@example.com" },
    {
      id: 49,
      name: "Michael Johnson",
      age: 29,
      email: "michael.johnson@example.com",
    },
    { id: 50, name: "Emily Davis", age: 31, email: "emily.davis@example.com" },
    { id: 1, name: "John Doe", age: 25, email: "john.doe@example.com" },
    { id: 2, name: "Jane Doe", age: 30, email: "jane.doe@example.com" },
    { id: 3, name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
    {
      id: 4,
      name: "Alice Johnson",
      age: 28,
      email: "alice.johnson@example.com",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 32,
      email: "michael.brown@example.com",
    },
    { id: 6, name: "Sarah Davis", age: 27, email: "sarah.davis@example.com" },
    { id: 7, name: "James Wilson", age: 29, email: "james.wilson@example.com" },
    { id: 8, name: "Linda Taylor", age: 31, email: "linda.taylor@example.com" },
    { id: 9, name: "David Lee", age: 26, email: "david.lee@example.com" },
    {
      id: 10,
      name: "Karen Anderson",
      age: 34,
      email: "karen.anderson@example.com",
    },
    {
      id: 11,
      name: "Paul Jackson",
      age: 33,
      email: "paul.jackson@example.com",
    },
    {
      id: 12,
      name: "Emily Harris",
      age: 29,
      email: "emily.harris@example.com",
    },
    {
      id: 13,
      name: "Christopher Young",
      age: 36,
      email: "christopher.young@example.com",
    },
    {
      id: 14,
      name: "Amanda Clark",
      age: 31,
      email: "amanda.clark@example.com",
    },
    {
      id: 15,
      name: "Matthew Turner",
      age: 30,
      email: "matthew.turner@example.com",
    },
    {
      id: 16,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 17, name: "Brian White", age: 28, email: "brian.white@example.com" },
    {
      id: 18,
      name: "Susan Harris",
      age: 35,
      email: "susan.harris@example.com",
    },
    {
      id: 19,
      name: "Daniel Taylor",
      age: 26,
      email: "daniel.taylor@example.com",
    },
    {
      id: 20,
      name: "Jessica Thompson",
      age: 32,
      email: "jessica.thompson@example.com",
    },
    { id: 21, name: "Mark Davis", age: 30, email: "mark.davis@example.com" },
    {
      id: 22,
      name: "Lisa Johnson",
      age: 29,
      email: "lisa.johnson@example.com",
    },
    {
      id: 23,
      name: "Robert Anderson",
      age: 33,
      email: "robert.anderson@example.com",
    },
    {
      id: 24,
      name: "Melissa Jackson",
      age: 31,
      email: "melissa.jackson@example.com",
    },
    {
      id: 25,
      name: "James Wilson",
      age: 27,
      email: "james.wilson@example.com",
    },
    {
      id: 26,
      name: "Jessica Taylor",
      age: 28,
      email: "jessica.taylor@example.com",
    },
    { id: 27, name: "Andrew Lee", age: 34, email: "andrew.lee@example.com" },
    { id: 28, name: "Sarah Brown", age: 25, email: "sarah.brown@example.com" },
    {
      id: 29,
      name: "Michael Johnson",
      age: 26,
      email: "michael.johnson@example.com",
    },
    { id: 30, name: "Emily Davis", age: 32, email: "emily.davis@example.com" },
    {
      id: 31,
      name: "David Harris",
      age: 30,
      email: "david.harris@example.com",
    },
    {
      id: 32,
      name: "Karen Wilson",
      age: 29,
      email: "karen.wilson@example.com",
    },
    {
      id: 33,
      name: "Christopher Martinez",
      age: 35,
      email: "christopher.martinez@example.com",
    },
    {
      id: 34,
      name: "Amanda Clark",
      age: 33,
      email: "amanda.clark@example.com",
    },
    {
      id: 35,
      name: "Matthew Turner",
      age: 28,
      email: "matthew.turner@example.com",
    },
    {
      id: 36,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 37, name: "Brian White", age: 36, email: "brian.white@example.com" },
    {
      id: 38,
      name: "Susan Harris",
      age: 32,
      email: "susan.harris@example.com",
    },
    {
      id: 39,
      name: "Daniel Taylor",
      age: 31,
      email: "daniel.taylor@example.com",
    },
    {
      id: 40,
      name: "Jessica Thompson",
      age: 29,
      email: "jessica.thompson@example.com",
    },
    { id: 41, name: "Mark Davis", age: 25, email: "mark.davis@example.com" },
    {
      id: 42,
      name: "Lisa Johnson",
      age: 26,
      email: "lisa.johnson@example.com",
    },
    {
      id: 43,
      name: "Robert Anderson",
      age: 34,
      email: "robert.anderson@example.com",
    },
    {
      id: 44,
      name: "Melissa Jackson",
      age: 33,
      email: "melissa.jackson@example.com",
    },
    {
      id: 45,
      name: "James Wilson",
      age: 28,
      email: "james.wilson@example.com",
    },
    {
      id: 46,
      name: "Jessica Taylor",
      age: 27,
      email: "jessica.taylor@example.com",
    },
    { id: 47, name: "Andrew Lee", age: 35, email: "andrew.lee@example.com" },
    { id: 48, name: "Sarah Brown", age: 30, email: "sarah.brown@example.com" },
    {
      id: 49,
      name: "Michael Johnson",
      age: 29,
      email: "michael.johnson@example.com",
    },
    { id: 50, name: "Emily Davis", age: 31, email: "emily.davis@example.com" },
    { id: 1, name: "John Doe", age: 25, email: "john.doe@example.com" },
    { id: 2, name: "Jane Doe", age: 30, email: "jane.doe@example.com" },
    { id: 3, name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
    {
      id: 4,
      name: "Alice Johnson",
      age: 28,
      email: "alice.johnson@example.com",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 32,
      email: "michael.brown@example.com",
    },
    { id: 6, name: "Sarah Davis", age: 27, email: "sarah.davis@example.com" },
    { id: 7, name: "James Wilson", age: 29, email: "james.wilson@example.com" },
    { id: 8, name: "Linda Taylor", age: 31, email: "linda.taylor@example.com" },
    { id: 9, name: "David Lee", age: 26, email: "david.lee@example.com" },
    {
      id: 10,
      name: "Karen Anderson",
      age: 34,
      email: "karen.anderson@example.com",
    },
    {
      id: 11,
      name: "Paul Jackson",
      age: 33,
      email: "paul.jackson@example.com",
    },
    {
      id: 12,
      name: "Emily Harris",
      age: 29,
      email: "emily.harris@example.com",
    },
    {
      id: 13,
      name: "Christopher Young",
      age: 36,
      email: "christopher.young@example.com",
    },
    {
      id: 14,
      name: "Amanda Clark",
      age: 31,
      email: "amanda.clark@example.com",
    },
    {
      id: 15,
      name: "Matthew Turner",
      age: 30,
      email: "matthew.turner@example.com",
    },
    {
      id: 16,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 17, name: "Brian White", age: 28, email: "brian.white@example.com" },
    {
      id: 18,
      name: "Susan Harris",
      age: 35,
      email: "susan.harris@example.com",
    },
    {
      id: 19,
      name: "Daniel Taylor",
      age: 26,
      email: "daniel.taylor@example.com",
    },
    {
      id: 20,
      name: "Jessica Thompson",
      age: 32,
      email: "jessica.thompson@example.com",
    },
    { id: 21, name: "Mark Davis", age: 30, email: "mark.davis@example.com" },
    {
      id: 22,
      name: "Lisa Johnson",
      age: 29,
      email: "lisa.johnson@example.com",
    },
    {
      id: 23,
      name: "Robert Anderson",
      age: 33,
      email: "robert.anderson@example.com",
    },
    {
      id: 24,
      name: "Melissa Jackson",
      age: 31,
      email: "melissa.jackson@example.com",
    },
    {
      id: 25,
      name: "James Wilson",
      age: 27,
      email: "james.wilson@example.com",
    },
    {
      id: 26,
      name: "Jessica Taylor",
      age: 28,
      email: "jessica.taylor@example.com",
    },
    { id: 27, name: "Andrew Lee", age: 34, email: "andrew.lee@example.com" },
    { id: 28, name: "Sarah Brown", age: 25, email: "sarah.brown@example.com" },
    {
      id: 29,
      name: "Michael Johnson",
      age: 26,
      email: "michael.johnson@example.com",
    },
    { id: 30, name: "Emily Davis", age: 32, email: "emily.davis@example.com" },
    {
      id: 31,
      name: "David Harris",
      age: 30,
      email: "david.harris@example.com",
    },
    {
      id: 32,
      name: "Karen Wilson",
      age: 29,
      email: "karen.wilson@example.com",
    },
    {
      id: 33,
      name: "Christopher Martinez",
      age: 35,
      email: "christopher.martinez@example.com",
    },
    {
      id: 34,
      name: "Amanda Clark",
      age: 33,
      email: "amanda.clark@example.com",
    },
    {
      id: 35,
      name: "Matthew Turner",
      age: 28,
      email: "matthew.turner@example.com",
    },
    {
      id: 36,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 37, name: "Brian White", age: 36, email: "brian.white@example.com" },
    {
      id: 38,
      name: "Susan Harris",
      age: 32,
      email: "susan.harris@example.com",
    },
    {
      id: 39,
      name: "Daniel Taylor",
      age: 31,
      email: "daniel.taylor@example.com",
    },
    {
      id: 40,
      name: "Jessica Thompson",
      age: 29,
      email: "jessica.thompson@example.com",
    },
    { id: 41, name: "Mark Davis", age: 25, email: "mark.davis@example.com" },
    {
      id: 42,
      name: "Lisa Johnson",
      age: 26,
      email: "lisa.johnson@example.com",
    },
    {
      id: 43,
      name: "Robert Anderson",
      age: 34,
      email: "robert.anderson@example.com",
    },
    {
      id: 44,
      name: "Melissa Jackson",
      age: 33,
      email: "melissa.jackson@example.com",
    },
    {
      id: 45,
      name: "James Wilson",
      age: 28,
      email: "james.wilson@example.com",
    },
    {
      id: 46,
      name: "Jessica Taylor",
      age: 27,
      email: "jessica.taylor@example.com",
    },
    { id: 47, name: "Andrew Lee", age: 35, email: "andrew.lee@example.com" },
    { id: 48, name: "Sarah Brown", age: 30, email: "sarah.brown@example.com" },
    {
      id: 49,
      name: "Michael Johnson",
      age: 29,
      email: "michael.johnson@example.com",
    },
    { id: 50, name: "Emily Davis", age: 31, email: "emily.davis@example.com" },
    { id: 1, name: "John Doe", age: 25, email: "john.doe@example.com" },
    { id: 2, name: "Jane Doe", age: 30, email: "jane.doe@example.com" },
    { id: 3, name: "Bob Smith", age: 35, email: "bob.smith@example.com" },
    {
      id: 4,
      name: "Alice Johnson",
      age: 28,
      email: "alice.johnson@example.com",
    },
    {
      id: 5,
      name: "Michael Brown",
      age: 32,
      email: "michael.brown@example.com",
    },
    { id: 6, name: "Sarah Davis", age: 27, email: "sarah.davis@example.com" },
    { id: 7, name: "James Wilson", age: 29, email: "james.wilson@example.com" },
    { id: 8, name: "Linda Taylor", age: 31, email: "linda.taylor@example.com" },
    { id: 9, name: "David Lee", age: 26, email: "david.lee@example.com" },
    {
      id: 10,
      name: "Karen Anderson",
      age: 34,
      email: "karen.anderson@example.com",
    },
    {
      id: 11,
      name: "Paul Jackson",
      age: 33,
      email: "paul.jackson@example.com",
    },
    {
      id: 12,
      name: "Emily Harris",
      age: 29,
      email: "emily.harris@example.com",
    },
    {
      id: 13,
      name: "Christopher Young",
      age: 36,
      email: "christopher.young@example.com",
    },
    {
      id: 14,
      name: "Amanda Clark",
      age: 31,
      email: "amanda.clark@example.com",
    },
    {
      id: 15,
      name: "Matthew Turner",
      age: 30,
      email: "matthew.turner@example.com",
    },
    {
      id: 16,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 17, name: "Brian White", age: 28, email: "brian.white@example.com" },
    {
      id: 18,
      name: "Susan Harris",
      age: 35,
      email: "susan.harris@example.com",
    },
    {
      id: 19,
      name: "Daniel Taylor",
      age: 26,
      email: "daniel.taylor@example.com",
    },
    {
      id: 20,
      name: "Jessica Thompson",
      age: 32,
      email: "jessica.thompson@example.com",
    },
    { id: 21, name: "Mark Davis", age: 30, email: "mark.davis@example.com" },
    {
      id: 22,
      name: "Lisa Johnson",
      age: 29,
      email: "lisa.johnson@example.com",
    },
    {
      id: 23,
      name: "Robert Anderson",
      age: 33,
      email: "robert.anderson@example.com",
    },
    {
      id: 24,
      name: "Melissa Jackson",
      age: 31,
      email: "melissa.jackson@example.com",
    },
    {
      id: 25,
      name: "James Wilson",
      age: 27,
      email: "james.wilson@example.com",
    },
    {
      id: 26,
      name: "Jessica Taylor",
      age: 28,
      email: "jessica.taylor@example.com",
    },
    { id: 27, name: "Andrew Lee", age: 34, email: "andrew.lee@example.com" },
    { id: 28, name: "Sarah Brown", age: 25, email: "sarah.brown@example.com" },
    {
      id: 29,
      name: "Michael Johnson",
      age: 26,
      email: "michael.johnson@example.com",
    },
    { id: 30, name: "Emily Davis", age: 32, email: "emily.davis@example.com" },
    {
      id: 31,
      name: "David Harris",
      age: 30,
      email: "david.harris@example.com",
    },
    {
      id: 32,
      name: "Karen Wilson",
      age: 29,
      email: "karen.wilson@example.com",
    },
    {
      id: 33,
      name: "Christopher Martinez",
      age: 35,
      email: "christopher.martinez@example.com",
    },
    {
      id: 34,
      name: "Amanda Clark",
      age: 33,
      email: "amanda.clark@example.com",
    },
    {
      id: 35,
      name: "Matthew Turner",
      age: 28,
      email: "matthew.turner@example.com",
    },
    {
      id: 36,
      name: "Jennifer Rodriguez",
      age: 27,
      email: "jennifer.rodriguez@example.com",
    },
    { id: 37, name: "Brian White", age: 36, email: "brian.white@example.com" },
    {
      id: 38,
      name: "Susan Harris",
      age: 32,
      email: "susan.harris@example.com",
    },
    {
      id: 39,
      name: "Daniel Taylor",
      age: 31,
      email: "daniel.taylor@example.com",
    },
    {
      id: 40,
      name: "Jessica Thompson",
      age: 29,
      email: "jessica.thompson@example.com",
    },
    { id: 41, name: "Mark Davis", age: 25, email: "mark.davis@example.com" },
    {
      id: 42,
      name: "Lisa Johnson",
      age: 26,
      email: "lisa.johnson@example.com",
    },
    {
      id: 43,
      name: "Robert Anderson",
      age: 34,
      email: "robert.anderson@example.com",
    },
    {
      id: 44,
      name: "Melissa Jackson",
      age: 33,
      email: "melissa.jackson@example.com",
    },
    {
      id: 45,
      name: "James Wilson",
      age: 28,
      email: "james.wilson@example.com",
    },
    {
      id: 46,
      name: "Jessica Taylor",
      age: 27,
      email: "jessica.taylor@example.com",
    },
    { id: 47, name: "Andrew Lee", age: 35, email: "andrew.lee@example.com" },
    { id: 48, name: "Sarah Brown", age: 30, email: "sarah.brown@example.com" },
    {
      id: 49,
      name: "Michael Johnson",
      age: 29,
      email: "michael.johnson@example.com",
    },
    { id: 50, name: "Emily Davis", age: 31, email: "emily.davis@example.com" },
  ];

  // TODO: write submit handler

  return (
    <React.Fragment>
      <SaveUser open={openModal} close={() => setOpenModal(false)} />

      <div className="relative">
        <div className="relative flex justify-between items-center mb-10">
          <div className="relative text-[2.4rem] font-semibold capitalize">
            Users list ({data.length})
          </div>
          <div>
            <button
              onClick={() => setOpenModal(true)}
              className="relative flex gap-3 items-center bg-[#3068ec] text-white px-12 py-4 text-[1.4rem] rounded-md font-medium capitalize"
            >
              <Icon className="text-[1.8rem]" icon="ic:baseline-plus" />
              <span>Create admin</span>
            </button>
          </div>
        </div>

        <div className="relative">
          <Table data={data} columns={columns} />
        </div>
      </div>
    </React.Fragment>
  );
};

export default Users;
