const PrivacyPolicy = () => {
  return (
    <div className="relative mt-[14rem] mb-[6rem] flex flex-col items-center justify-center w-[85%] mx-auto ">
      <div className="relative font-medium text-[5.5rem] mb-12 capitalize">Privacy Policy</div>
      <div className="relative text-[2rem] font-medium">
        <p className="relative mb-12">
          This document is an electronic record in terms of Information
          Technology Act, 2000 & rules thereunder as applicable and the amended
          provisions pertaining to electronic records in various statutes as
          amended by the Information Technology Act, 2000. This electronic
          record is generated by a computer system and does not require any
          physical or digital signatures. This document is published in
          accordance with the provisions of Rule 3 (1) of the Information
          Technology (Intermediaries guidelines) Rules, 2011 that require
          publishing the rules and regulations, privacy policy and Terms of Use
          for access or usage of www.rkpattarai.com Please read the following
          terms and conditions very carefully as your use of service is subject
          to your acceptance of and compliance with the following terms and
          conditions (“Terms”). By subscribing to or using any of our services
          you agree that you have read, understood and are bound by the Terms,
          regardless of how you subscribe to or use the services. If you do not
          want to be bound by the Terms, you must not subscribe to or use our
          services.
        </p>

        <p className="relative mb-12">
          Usage Restrictions You shall not use the Website/app/chatbot for any
          of the following purposes: Disseminating any unlawful, harassing,
          libelous, abusive, threatening, harmful, vulgar, obscene, or otherwise
          objectionable material Transmitting material that encourages conduct
          that constitutes a criminal offence, results in civil liability or
          otherwise breaches any relevant laws, regulations or code of practice.
        </p>

        <p className="relative mb-12">
          Gaining unauthorized access to other computer systems. Interfering
          with any other person’s use or enjoyment of the Website/app/chatbot.
          Breaching any applicable laws; Interfering or disrupting networks or
          website/app/chatbot connected to the Website/app/chatbot. Making,
          transmitting or storing electronic copies of materials protected by
          copyright without the permission owner.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
