spring:
  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://test-db.ctkugamfpuak.us-east-1.rds.amazonaws.com:3306/abicoirr?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: WmDlcwrbp4iAJ3Fh
    password: q$tlLjhGRSb*
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO

application:
  url: <prod load balancer url>
  backend-url: http://instance-lb-1280422799.us-east-1.elb.amazonaws.com
  frontend-url: http://instance-lb-1280422799.us-east-1.elb.amazonaws.com