spring:
  application:
    name: abicoirr-backend
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 15MB # Maximum file size allowed
      max-request-size: 50MB  # Maximum request size allowed
  flyway:
    enabled: true
    table: flyway_schema_table

server:
  servlet:
    context-path: /api/v1
  port: 8000
